### ISSUE TITLE
Wrong Condition: State NOT in suggested states

### ISSUE THREAD

**Issue by LMCom** [hyn/state-machine#2]
If a next state is specified, it should actually be in the suggested states of a transition, which is checked to be a possible next transition. It seems wrong, that the code negates `in_array()`.

https://github.com/hyn/state-machine/blob/5503316ec851b28e1d6ec45b8bee2d3c83dd9b7d/src/Statemachine.php#L174

**Comment by LMCom** [comment]
On a second thought, does it even play a role, if the next state is in the suggested states of the possible transitions?

**Comment by luceos** [comment]
I think you're right that negation is incorrect. What it tries to do is, if you provide a wished for next state to identify which of the transitions suits the needs to transition to that state. The negation blocks that functionality.

Are you willing to provide a PR for this?

**Comment by LMCom** [comment]
Sorry, I am currently exclusively programming for work and very busy and I am actually not using your state-machine. I just looked through the code for inspiration, because I have to do something similar. However, it will be quite configurable, so it will make use of a database, where possible. Your state-machine is really nice, but not suited in this case.

Thanks for your quick reply!

**Comment by luceos** [comment]
No problem, glad this package has at least some use. I'm not using it anymore, but keeping it available to the public does obviously help.

Good luck with writing one of your own, it's a bit of a challenge but extremely fun to do!

**Comment by luceos** [comment]
closed in https://github.com/hyn/state-machine/commit/5ba826e707a9a34afd51315766a60976aa4d7750
